

    - name: Create directory if it doesn't exist
      file:
        path: /tmp/PRECHECKS/{{ cr_number }}
        state: directory
        mode: '0755'
    - name: kernel version before
      shell: uname -r > /tmp/PRECHECKS/{{ cr_number }}/uname_pre.txt
      
    - name: register kernel version
      shell: uname -r
      register: uname_pre
      
    - name: /etc/os-release
      shell: cat /etc/os-release > /tmp/PRECHECKS/{{ cr_number }}/osversion_pre.txt
      
    - name: register /etc/os-release
      shell: cat /etc/os-release
      register: osversion_pre

    - name: ifconfig
      shell: ifconfig > /tmp/PRECHECKS/{{ cr_number }}/ifconfig_pre.txt
      
    - name: ifconfig
      shell: ifconfig
      register: ifconfig_pre
      
    - name: Uptime of the server  
      shell: uptime > /tmp/PRECHECKS/{{ cr_number }}/uptime_pre.txt
      
    - name: Uptime of the server  
      shell: uptime
      register: uptime_pre
         
    - name: filesystems details
      shell: df -Th > /tmp/PRECHECKS/{{ cr_number }}/df_pre.txt
      
    - name: filesystems details
      shell: df -Th
      register: disk_pre
    
    - name: Fetch /etc/fstab content
      fetch:
        src: /etc/fstab
        dest: /tmp/PRECHECKS/{{ cr_number }}/fstab_pre.txt

    - name: Read /etc/fstab content and register as a variable
      shell: cat /etc/fstab
      register: fstab_pre
      
    - name: Get file status
      stat:
        path: /proc/mount
      register: file_status

    - name: Save file content if it exists
      shell: cat /proc/mounts > /tmp/PRECHECKS/{{ cr_number }}/proc_mount_pre.txt
      when: file_status.stat.exists
      
    - name: register file content if it exists
      shell: cat /proc/mounts
      register: proc_mount_pre
      when: file_status.stat.exists

    - name: Read /etc/hosts file
      shell: cat /etc/hosts > /tmp/PRECHECKS/{{ cr_number }}/hosts_pre.txt
 
    - name: Read /etc/hosts file
      shell: cat /etc/hosts
      register: hosts_pre
      
    - name: /etc/passwd details
      shell: cat /etc/passwd > /tmp/PRECHECKS/{{ cr_number }}/passwd_pre.txt
      
    - name: /etc/passwd details
      shell: cat /etc/passwd
      register: passwd_pre
      
    - name: /etc/group details
      shell: cat /etc/group > /tmp/PRECHECKS/{{ cr_number }}/group_pre.txt
      
    - name: /etc/group details
      shell: cat /etc/group
      register: group_pre
      
    - name: /etc/shadow details
      shell: cat /etc/shadow > /tmp/PRECHECKS/{{ cr_number }}/shadow_pre.txt
      
    - name: /etc/group details
      shell: cat /etc/shadow
      register: shadow_pre
      
    - name: /etc/sysctl.conf details
      shell: cat /etc/sysctl.conf > /tmp/PRECHECKS/{{ cr_number }}/sysctl_pre.txt
    
    - name: /etc/sysctl.conf details
      shell: cat /etc/sysctl.conf
      register: sysctl_pre
      
    - name: vg and lv details
      shell: vgs;lvs > /tmp/PRECHECKS/{{ cr_number }}/vgs_lvs_pre.txt
    
    - name: vg and lv details
      shell: vgs;lvs
      register: vgs_lvs_pre
      
    - name: Check if backup service is running on the server
      shell: systemctl status dsmcad > /tmp/PRECHECKS/{{ cr_number }}/dsmcad_pre.txt
      
    - name: save the backup service status
      shell: systemctl status dsmcad
      register: dsmcad_pre
      
    - name: Check if postfix service is running on the server
      shell: systemctl status postfix > /tmp/PRECHECKS/{{ cr_number }}/postfix_pre.txt
      
    - name: save the backup service status
      shell: systemctl status postfix
      register: postfix_pre
      
    - name: Check if oneagent service is running on the server
      shell: systemctl status oneagent > /tmp/PRECHECKS/{{ cr_number }}/oneagent_pre.txt
      
    - name: save the backup service status
      shell: systemctl status oneagent
      register: oneagent_pre
      
    - name: get netstat -nr output
      shell: netstat -nr > /tmp/PRECHECKS/{{ cr_number }}/netstat_pre.txt
      
    - name: Save the netstat -nr output
      shell: netstat -nr
      register: netstat_pre
      
    - name: get selinux status
      shell: getenforce > /tmp/PRECHECKS/{{ cr_number }}/selinux_pre.txt

    - name: save selinux status
      shell: getenforce
      register: selinux_pre
      
    - name: Save all output to a single file
      ansible.builtin.blockinfile:
        path: /tmp/PRECHECKS/{{ cr_number }}/precheck_output.txt
        block: |
          ==========================
          uptime of the server:
          {{ uptime_pre.stdout }}
          
          ==========================
          Kernel Version Before:
          {{ uname_pre.stdout }}
          
          ==========================
          ifconfig Output:
          {{ ifconfig_pre.stdout }}
          
          ==========================
          Filesystem Details:
          {{ disk_pre.stdout }}
          
          ==========================
          /etc/fstab content:
          {{ fstab_pre.stdout }}
          
          ==========================
          /etc/hosts Content:
          {{ hosts_pre.stdout }}
          
          ==========================
          /etc/passwd details:
          {{ passwd_pre.stdout }}
          
          ==========================
          /etc/group details:
          {{ group_pre.stdout }}
          
          =========================
          /etc/shadow details:
          {{ shadow_pre.stdout }}
          
          =========================
          VG and LV details:
          {{ vgs_lvs_pre.stdout }}
          
          =========================
          OS Version details:
          {{ osversion_pre.stdout }}
          =========================
          backup service status:
          {{ dsmcad_pre.stdout }}
          
          =========================
          Oneagent service status:
          {{ oneagent_pre.stdout }}
          
          =========================
          postfix service status
          {{ postfix_pre.stdout }}
          
          =========================
          netstat -nr output:
          {{ netstat_pre.stdout }}
          
          =========================
          Selinux sttus on the server:
          {{ selinux_pre.stdout }}
          
          =========================
          
        create: yes
        
    - name: add /proc/mount detail if exist
      ansible.builtin.blockinfile:
        path: /tmp/PRECHECKS/{{ cr_number }}/precheck_output.txt
        block: |
          ==========================
          /proc/mount content:
          {{ proc_mount_pre.stdout }}
          
          ==========================
      when: file_status.stat.exists
        
        
    - name: Send email with attachment
      shell: "echo '<b><i>Please find the attachment</i></b>' | mailx -s 'Attachment from Ansible' -a /tmp/PRECHECKS/{{ cr_number }}/precheck_output.txt {{ email_address }}"